export const creatorRoles = [
  "bassist",
  "DJ",
  "drummer",
  "guitarist",
  "instrumentalist",
  "mix engineer",
  "pianist",
  "producer",
  "rapper",
  "songwriter",
  "vocalist",
] as const;

export const musicGenres = [
  "afrobeats",
  "amapiano",
  "blues",
  "classical",
  "country",
  "dancehall",
  "drill",
  "electronic",
  "folk",
  "gospel",
  "grime",
  "hip hop",
  "house",
  "indie",
  "jazz",
  "latin",
  "metal",
  "neo soul",
  "pop",
  "r&b",
  "reggae",
  "rock",
  "soul",
  "trap",
] as const;

export const locationSuggestions = [
  "London, UK",
  "Berlin, Germany",
  "Toronto, Canada",
  "Lagos, Nigeria",
  "Accra, Ghana",
  "Los Angeles, USA",
  "New York, USA",
  "Paris, France",
  "Amsterdam, Netherlands",
  "Tokyo, Japan",
  "Sydney, Australia",
  "Mumbai, India",
  "Sao Paulo, Brazil",
  "Mexico City, Mexico",
  "Stockholm, Sweden",
] as const;
