export const creatorRoles = [
  "vocalist",
  "music producer",
  "producer",
  "rapper",
  "guitarist",
  "filmmaker",
  "photographer",
  "graphic designer",
  "designer",
  "dancer",
  "comedian",
  "poet",
  "songwriter",
  "beatmaker",
  "dj",
  "director",
  "editor",
  "animator",
] as const;

export const locationSuggestions = [
  "London, UK",
  "Berlin, Germany",
  "Toronto, Canada",
  "Lagos, Nigeria",
  "Accra, Ghana",
  "Los Angeles, USA",
  "New York, USA",
  "Paris, France",
  "Amsterdam, Netherlands",
  "Tokyo, Japan",
  "Sydney, Australia",
  "Mumbai, India",
  "Sao Paulo, Brazil",
  "Mexico City, Mexico",
  "Stockholm, Sweden",
] as const;
