import { dark, panel, panelSoft, border, muted } from "@/theme/tokens";

export const mediaOverlayStyleNames = new Set([
  "topSheet",
  "topSheetScroll",
  "topSheetScrollContent",
  "filterSheetSection",
  "filterLookingForRow",
  "filterLookingForControl",
  "filterLookingForLabel",
  "filterLookingForIconSlot",
  "sectionLabelLight",
  "locationFilterList",
  "locationCountryGroup",
  "locationOptionRow",
  "locationCircle",
  "locationCityCircle",
  "locationCircleSelected",
  "locationCirclePartial",
  "locationCirclePartialFill",
  "locationCountryText",
  "locationCityList",
  "locationCityRow",
  "locationCityText",
  "feedRoot",
  "feedBootOverlay",
  "feedName",
  "feedRole",
  "feedRecentFilterText",
  "feedRecentFilterTextActive",
  "caption",
  "feedCaptionText",
  "feedLookingForIcon",
  "tag",
  "badge",
  "actionText",
  "jamJarLid",
  "jamJarLidSent",
  "jamJarLidSolidFill",
  "jamJarBody",
  "jamJarAnimatedFill",
  "jamJarSmoothWaveSurface",
  "jamJarBumpWaveWrap",
  "jamJarLeak",
  "jamJarLeakDrop",
  "jamJarLeakDropSide",
  "jamJarFill",
  "jamJarFillSent",
  "jamJarEmptyJam",
  "jamJarWaveLeft",
  "jamJarWaveRight",
  "gridCaption",
  "lockedText",
  "videoPlaceholder",
  "feedTopShade",
  "feedBottomShade",
  "fullscreenVideoRoot",
  "fullscreenAdjacentVideo",
  "fullscreenMessageRoot",
  "fullscreenMessageBar",
  "fullscreenMessageInput",
  "fullscreenMessageSendFrame",
  "fullscreenMessageSendButton",
  "fullscreenMessageSendText",
  "fullscreenMessageSentTick",
  "feedItem",
  "feedVideoLayer",
  "createEditNextBand",
  "createEditNextPill",
  "createEditNextText",
  "createEditToolPanel",
  "createTrimToolPanel",
  "createTrimToolPanelContent",
  "createEditUploadProgressWrap",
  "createFilterOverlay",
  "createTextOverlayDraggable",
  "createTextOverlaySnapGuideVertical",
  "createTextOverlaySnapGuideHorizontal",
  "createTextOverlayPreviewText",
  "createTextOverlayInput",
  "createTextOverlayActionMenu",
  "createTextOverlayActionCaret",
  "createTextOverlayActionBubble",
  "createTextOverlayActionButton",
  "createTextOverlayActionButtonText",
  "createTextOverlayActionEffectButton",
  "createTextOverlayActionEffectGlyph",
  "createTextOverlayActionDeleteText",
  "createTextOverlayActionDivider",
  "createTrimHeader",
  "createTrimDuration",
  "createTrimFilmstripOuter",
  "createTrimFilmstrip",
  "createTrimFilmstripLoading",
  "createTrimFilmstripFrames",
  "createTrimFilmstripFrame",
  "createTrimFilmstripFramePlaceholder",
  "createTrimFilmstripDim",
  "createTrimFilmstripSelection",
  "createTrimHandleTab",
  "createTrimHandleTabStart",
  "createTrimHandleTabStartFlush",
  "createTrimHandleTabEnd",
  "createTrimHandleTabEndFlush",
  "createFilterList",
  "createFilterOption",
  "createFilterThumbRing",
  "createFilterThumbRingActive",
  "createFilterThumbInner",
  "createFilterThumbInnerCompact",
  "createTextFontThumbInner",
  "createTextFontThumbSample",
  "createFilterThumbImage",
  "createFilterThumbFallback",
  "createFilterLabel",
  "createFilterNameFlashRoot",
  "createFilterNameFlashText",
  "createEditUploadProgress",
  "createCameraRoot",
  "createCameraViewport",
  "createCameraPermission",
  "createCameraTapLayer",
  "createCameraFocusReticle",
  "createCameraFocusReticleCircle",
  "createCameraExposureRail",
  "createCameraExposureLine",
  "createCameraExposureDot",
  "createCameraFilterPreview",
  "createCameraScreenFlash",
  "createCameraCountdownOverlay",
  "createCameraCountdownText",
  "createCameraTopBar",
  "createCameraSideRail",
  "createCameraControlButton",
  "createCameraSideRailText",
  "createCameraCloseIconText",
  "createCameraFilterSheetWrap",
  "createCameraFilterDismiss",
  "createCameraFilterBand",
  "createCameraFilterFloat",
  "createCameraBottomBar",
  "createLibraryButton",
  "createLibraryThumbnail",
  "createRecordButton",
  "createCameraHint",
]);


export function createLightStyles<T extends Record<string, unknown>>(source: T): T {
  return Object.fromEntries(
    Object.entries(source).map(([key, value]) => [
      key,
      mediaOverlayStyleNames.has(key) ? value : transformStyleForLightMode(value),
    ]),
  ) as T;
}

function transformStyleForLightMode(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map(transformStyleForLightMode);
  }

  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value).map(([key, nestedValue]) => [
        key,
        key.toLowerCase().includes("shadow")
          ? nestedValue
          : transformStyleForLightMode(nestedValue),
      ]),
    );
  }

  if (typeof value !== "string") return value;
  return getLightModeColor(value);
}

function getLightModeColor(value: string) {
  const colorMap: Record<string, string> = {
    [dark]: "#f7f7f8",
    [panel]: "#ffffff",
    [panelSoft]: "#f2f2f4",
    [border]: "rgba(0,0,0,0.12)",
    [muted]: "#52525b",
    "#fff": "#0a0a0a",
    "#000": "#ffffff",
    "#09090b": "#ffffff",
    "#27272a": "#e4e4e7",
    "#e4e4e7": "#27272a",
    "#d4d4d8": "#3f3f46",
    "#8b8b95": "#52525b",
    "#71717a": "#71717a",
    "#52525b": "#71717a",
    "rgba(10,10,10,0.96)": "rgba(255,255,255,0.96)",
    "rgba(9,9,11,0.98)": "rgba(255,255,255,0.98)",
    "rgba(9,9,11,0.96)": "rgba(255,255,255,0.96)",
    "rgba(9,9,11,0.94)": "rgba(255,255,255,0.96)",
    "rgba(9,9,11,0.92)": "rgba(255,255,255,0.94)",
    "rgba(24,24,27,0.82)": "rgba(255,255,255,0.88)",
    "rgba(255,255,255,0.14)": "rgba(0,0,0,0.14)",
    "rgba(255,255,255,0.20)": "rgba(0,0,0,0.10)",
    "rgba(255,255,255,0.28)": "rgba(0,0,0,0.28)",
    "rgba(255,255,255,0.10)": "rgba(0,0,0,0.08)",
    "rgba(0,0,0,0.42)": "rgba(0,0,0,0.18)",
    "rgba(0,0,0,0.62)": "rgba(0,0,0,0.20)",
    "rgba(0,0,0,0.58)": "rgba(255,255,255,0.58)",
  };
  return colorMap[value] ?? value;
}
