import { Platform, StyleSheet, type ImageStyle, type StyleProp, type TextStyle, type ViewStyle } from "react-native";
import type { ThemeMode } from "@/types/app";
import { createLightStyles } from "@/theme/light";
import {
  CREATE_CAMERA_CONTROL_BUTTON_SIZE,
  CREATE_CAMERA_FOCUS_RETICLE_SIZE,
  CREATE_CAMERA_RECORD_BUTTON_BORDER_WIDTH,
  CREATE_CAMERA_RECORD_BUTTON_SIZE,
  CREATE_DETAILS_PREVIEW_HEIGHT,
  CREATE_DETAILS_PREVIEW_WIDTH,
  CREATE_FILTER_THUMB_BORDER_WIDTH,
  CREATE_THUMBNAIL_FILMSTRIP_FRAME_HEIGHT,
  CREATE_TRIM_FILMSTRIP_HEIGHT,
  CREATE_TRIM_FILMSTRIP_RADIUS,
  CREATE_TRIM_HANDLE_WIDTH,
  FEED_ACTION_GAP,
  FEED_CHROME_LOCK_CIRCLE_SIZE,
  FEED_PREVIEW_VIDEO_BOTTOM_CORNER_RADIUS,
  FEED_SPEED_PILL_HEIGHT,
  FEED_SPEED_PILL_PADDING_V,
  FEED_SPEED_PILL_WIDTH,
  FEED_SPEED_ROW_HEIGHT,
  FEED_VIDEO_BOTTOM_CORNER_RADIUS,
  NAV_BAR_HEIGHT,
  NAV_BAR_ITEM_HEIGHT,
  PROFILE_COLLAPSED_BAR_HEIGHT,
  PROFILE_GRID_GAP,
  PROFILE_GRID_ITEM_WIDTH,
  SCREEN_CONTENT_PADDING,
  TEXT_OVERLAY_BASE_FONT_SIZE,
  WELCOME_HEADER_TAP_GUARD,
  border,
  dark,
  muted,
  overlayTextShadow,
  panel,
  panelSoft,
  viewportHeight,
  viewportWidth,
} from "@/theme/tokens";

export let activeThemeMode: ThemeMode = "dark";

export function setActiveThemeMode(mode: ThemeMode) {
  activeThemeMode = mode;
}

export function getActivityIndicatorColor() {
  return activeThemeMode === "light" ? "#0a0a0a" : "#fff";
}

const baseStyles = {
  gestureRoot: { flex: 1, backgroundColor: dark },
  swipeBackSurface: { flex: 1, backgroundColor: dark },
  profileStackOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: dark, zIndex: 20 },
  fullscreenOverlay: { ...StyleSheet.absoluteFillObject, zIndex: 60, elevation: 60 },
  app: { flex: 1, backgroundColor: dark },
  tabScene: { backgroundColor: dark },
  safe: { flex: 1, backgroundColor: dark },
  safeWithNav: { flex: 1, paddingBottom: NAV_BAR_HEIGHT, backgroundColor: dark },
  profileScrollFadeRoot: { flex: 1 },
  profileScrollTopFade: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 2,
  },
  profileCollapsedBar: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 3,
    backgroundColor: dark,
    borderBottomWidth: 1,
    borderBottomColor: border,
  },
  profileCollapsedBarContent: {
    height: PROFILE_COLLAPSED_BAR_HEIGHT,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: SCREEN_CONTENT_PADDING,
  },
  profileCollapsedBarTitle: {
    flex: 1,
    color: "#fff",
    fontSize: 17,
    fontWeight: "800",
    letterSpacing: -0.4,
  },
  flex: { flex: 1 },
  centered: { flex: 1, alignItems: "center", justifyContent: "center", gap: 14, padding: 24 },
  authCard: { width: "100%", gap: 14 },
  onboardingHeader: {
    paddingHorizontal: 16,
    paddingTop: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  onboardingBackButton: {
    minWidth: 40,
    minHeight: 40,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  onboardingBackButtonHidden: { opacity: 0 },
  onboardingBackText: { color: "#fff", fontSize: 28, lineHeight: 30, fontWeight: "600" },
  onboardingHeaderSpacer: { width: 40, height: 40 },
  onboardingProgressRow: { flexDirection: "row", gap: 6, paddingHorizontal: 16, paddingTop: 12, paddingBottom: 8 },
  onboardingProgressSegment: { flex: 1, height: 4, borderRadius: 999, backgroundColor: "rgba(255,255,255,0.14)" },
  onboardingProgressSegmentActive: { backgroundColor: "#fff" },
  onboardingStepsViewport: { flex: 1, overflow: "hidden" },
  onboardingStepsTrack: { flexDirection: "row", flex: 1 },
  onboardingStepPanel: { width: viewportWidth },
  onboardingContent: { flexGrow: 1, gap: 14, paddingHorizontal: 24, paddingTop: 12, paddingBottom: 24 },
  onboardingPhotoContent: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
    paddingBottom: 32,
    gap: 32,
  },
  onboardingPhotoIntro: { alignItems: "center", gap: 8, paddingHorizontal: 12 },
  onboardingPhotoTitle: { textAlign: "center" },
  onboardingPhotoCopy: { textAlign: "center" },
  onboardingFooter: { flexShrink: 0, gap: 10, paddingHorizontal: 24, paddingTop: 8, alignItems: "stretch" },
  onboardingFooterButton: { flex: 0, width: "100%" },
  onboardingAvatarPicker: { alignItems: "center", justifyContent: "center", gap: 20, width: "100%", maxWidth: 320 },
  onboardingAvatarActions: { flexDirection: "row", gap: 20, alignItems: "center", justifyContent: "center" },
  onboardingAvatarActionButton: { paddingVertical: 8, paddingHorizontal: 4 },
  onboardingAvatarActionText: { color: "#fff", fontSize: 17, fontWeight: "700", textTransform: "lowercase" },
  onboardingSkipButton: { minHeight: 44, alignItems: "center", justifyContent: "center" },
  onboardingSkipText: { color: muted, fontSize: 15, fontWeight: "600", textTransform: "lowercase" },
  welcomeStage: { flex: 1 },
  welcomeHeaderOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    minHeight: WELCOME_HEADER_TAP_GUARD,
    paddingTop: 8,
    paddingHorizontal: 16,
    zIndex: 10,
    elevation: 10,
  },
  welcomeBeat: { justifyContent: "center", alignItems: "center", paddingHorizontal: 28 },
  welcomeBeatLayer: { ...StyleSheet.absoluteFillObject },
  welcomeIntroText: {
    color: muted,
    fontSize: 16,
    textTransform: "lowercase",
    letterSpacing: 0.4,
    textAlign: "center",
  },
  welcomePositionText: { textAlign: "center" },
  welcomePositionLayout: { flex: 1, width: "100%" },
  welcomePositionTextWrap: { flex: 1, justifyContent: "center", alignItems: "center", paddingHorizontal: 28 },
  welcomeForwardHint: { color: "#fff", fontSize: 28, lineHeight: 30, fontWeight: "600" },
  welcomeForwardHintPositioned: { position: "absolute", left: 0, right: 0, textAlign: "center" },
  welcomeMessagePage: { ...StyleSheet.absoluteFillObject, width: "100%" },
  welcomeMessageOneLayout: { flex: 1, width: "100%" },
  welcomeMessageOneTop: {
    flex: 1,
    justifyContent: "flex-end",
    alignItems: "center",
    paddingHorizontal: SCREEN_CONTENT_PADDING,
    paddingBottom: 16,
  },
  welcomeMessageOneCenter: { paddingHorizontal: SCREEN_CONTENT_PADDING, alignItems: "center" },
  welcomeMessageOneBottom: { flex: 1 },
  welcomeMessageTwoContent: {
    width: "100%",
    paddingHorizontal: SCREEN_CONTENT_PADDING,
    gap: 24,
  },
  welcomeBackTapZone: {
    position: "absolute",
    top: WELCOME_HEADER_TAP_GUARD,
    bottom: 0,
    left: 0,
    width: viewportWidth * 0.2,
    zIndex: 5,
  },
  welcomeMessageTwoButton: { flex: 0, alignSelf: "stretch" },
  welcomeMessageOneCopy: { textAlign: "center", fontSize: 15, lineHeight: 26 },
  welcomeCallout: {
    color: "#fff",
    fontSize: 34,
    fontWeight: "800",
    lineHeight: 42,
    textAlign: "center",
    letterSpacing: -0.8,
  },
  authLogoWrap: { alignItems: "center", justifyContent: "center" },
  authWelcomeTo: {
    position: "absolute",
    bottom: "100%",
    marginBottom: 2,
    color: "#fff",
    fontSize: 34,
    fontWeight: "800",
    letterSpacing: -1.5,
    textAlign: "center",
    textTransform: "lowercase",
  },
  logo: { color: "#fff", fontSize: 58, fontWeight: "800", letterSpacing: -3, textAlign: "center" },
  logoSmall: { color: "#fff", fontSize: 42, fontWeight: "800", letterSpacing: -2 },
  h1: { color: "#fff", fontSize: 34, fontWeight: "800", letterSpacing: -1.2, lineHeight: 40 },
  h2: { color: "#fff", fontSize: 27, fontWeight: "800", letterSpacing: -0.6 },
  subtitle: { color: muted, fontSize: 15, lineHeight: 22 },
  copy: { color: "#d4d4d8", fontSize: 15, lineHeight: 22 },
  copyCentered: { color: "#d4d4d8", fontSize: 15, lineHeight: 23, textAlign: "center" },
  profileBio: { color: "#f4f4f5", fontSize: 15, lineHeight: 23, textAlign: "center" },
  longCopy: { color: "#d4d4d8", fontSize: 17, lineHeight: 30 },
  eyebrow: { color: muted, fontSize: 14, textTransform: "lowercase", letterSpacing: 0.4 },
  screenContent: { padding: SCREEN_CONTENT_PADDING, gap: 16 },
  input: { minHeight: 52, borderRadius: 18, borderWidth: 1, borderColor: border, color: "#fff", backgroundColor: panel, paddingHorizontal: 16, fontSize: 16 },
  filterQueryRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  filterQueryInput: { flex: 1, minWidth: 0 },
  filterResetButton: { minHeight: 52, minWidth: 52, alignItems: "center", justifyContent: "center" },
  filterResetIcon: { color: muted, fontSize: 20, fontWeight: "600", lineHeight: 22 },
  textArea: { minHeight: 112, paddingTop: 14, textAlignVertical: "top" },
  primaryButton: { minHeight: 48, flex: 1, alignItems: "center", justifyContent: "center", borderRadius: 16, backgroundColor: "#fff", paddingHorizontal: 16 },
  primaryButtonText: { color: "#000", fontSize: 16, fontWeight: "800", textTransform: "lowercase" },
  profileJamRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    gap: 6,
  },
  profileActionPill: {
    minHeight: 48,
    minWidth: 190,
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 999,
    backgroundColor: "#3f3f46",
    paddingHorizontal: 24,
  },
  profileActionPillText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "700",
    textTransform: "lowercase",
  },
  profileJamButton: {
    minWidth: 190,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 999,
    backgroundColor: "#3f3f46",
    paddingHorizontal: 24,
  },
  profileJamButtonJamming: { backgroundColor: "#52525b" },
  profileJamButtonText: { color: "#fff", fontSize: 16, fontWeight: "800" },
  profileJamButtonTextJamming: { color: "#fff" },
  profileJamCancelButton: {
    width: 48,
    height: 48,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ef4444",
  },
  profileJamCancelIcon: {
    color: "#fff",
    fontSize: 26,
    fontWeight: "700",
    lineHeight: 28,
    marginTop: -1,
  },
  secondaryButton: { minHeight: 48, flex: 1, alignItems: "center", justifyContent: "center", borderRadius: 16, borderWidth: 1, borderColor: border, backgroundColor: panel, paddingHorizontal: 16 },
  secondaryButtonText: { color: "#fff", fontSize: 16, fontWeight: "700", textTransform: "lowercase" },
  destructiveButton: { minHeight: 48, flex: 1, alignItems: "center", justifyContent: "center", borderRadius: 16, borderWidth: 1, borderColor: "rgba(252,165,165,0.45)", backgroundColor: "rgba(239,68,68,0.18)", paddingHorizontal: 16 },
  destructiveButtonText: { color: "#fca5a5", fontSize: 16, fontWeight: "800", textTransform: "lowercase" },
  confirmOption: { flex: 1, minHeight: 44, alignItems: "center", justifyContent: "center" },
  confirmOptionCancelText: { color: "#d4d4d8", fontSize: 16, fontWeight: "700", textTransform: "lowercase" },
  confirmOptionDangerText: { color: "#fca5a5", fontSize: 16, fontWeight: "800", textTransform: "lowercase" },
  disabled: { opacity: 0.45 },
  switchText: { color: muted, textAlign: "center", marginTop: 6, textTransform: "lowercase" },
  forgotPasswordText: {
    color: muted,
    textAlign: "right",
    marginTop: -4,
    marginBottom: 2,
    fontSize: 14,
    textTransform: "lowercase",
  },
  notice: { color: "#bbf7d0", textAlign: "center", padding: 12, borderRadius: 14, backgroundColor: "rgba(22,101,52,0.18)" },
  error: { color: "#fca5a5", textAlign: "center" },
  helper: { color: "#71717a", fontSize: 13, lineHeight: 18 },
  charCount: { alignSelf: "flex-end", color: "#71717a", fontSize: 12 },
  jamPromptMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  jamLimitReachedText: { color: "#fca5a5" },
  loader: { marginTop: 28 },
  sectionLabel: { color: "#8b8b95", fontSize: 12, fontWeight: "700", letterSpacing: 0.8, textTransform: "uppercase", marginTop: 4 },
  sectionLabelLight: { color: "#fff" },
  chips: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  chip: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 999, borderWidth: 1, borderColor: border, backgroundColor: panel },
  chipText: { color: "#e4e4e7", fontSize: 14 },
  categoryGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  categoryOption: { paddingHorizontal: 12, paddingVertical: 9, borderRadius: 999, borderWidth: 1, borderColor: border, backgroundColor: panelSoft },
  categoryOptionActive: { borderColor: "#fff", backgroundColor: "#fff" },
  categoryOptionText: { color: "#e4e4e7", fontSize: 14, fontWeight: "700" },
  categoryOptionTextActive: { color: "#000" },
  suggestionList: { overflow: "hidden", borderRadius: 18, borderWidth: 1, borderColor: border, backgroundColor: panel },
  suggestionItem: { paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: border },
  suggestionText: { color: "#e4e4e7", fontSize: 15 },
  profileLocationPicker: { gap: 10 },
  locationFilterList: { overflow: "hidden", borderRadius: 18, borderWidth: 1, borderColor: border, backgroundColor: panel },
  locationCountryGroup: { borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: border },
  locationOptionRow: { minHeight: 50, flexDirection: "row", alignItems: "center", gap: 12, paddingHorizontal: 16, paddingVertical: 12 },
  locationCircle: { width: 20, height: 20, alignItems: "center", justifyContent: "center", borderRadius: 10, borderWidth: 1.5, borderColor: "#fff" },
  locationCityCircle: { width: 16, height: 16, borderRadius: 8, borderWidth: 1.25, borderColor: "#d4d4d8" },
  locationCircleSelected: { backgroundColor: "#fff" },
  locationCirclePartial: { backgroundColor: "transparent" },
  locationCirclePartialFill: { width: 10, height: 10, borderRadius: 5, backgroundColor: "#fff" },
  locationCountryText: { flex: 1, color: "#f4f4f5", fontSize: 16, fontWeight: "700" },
  locationCityList: { gap: 2, paddingBottom: 8 },
  locationCityRow: { minHeight: 38, flexDirection: "row", alignItems: "center", gap: 10, paddingLeft: 48, paddingRight: 16, paddingVertical: 8 },
  locationCityText: { color: "#d4d4d8", fontSize: 14, fontWeight: "600" },
  row: { flexDirection: "row", alignItems: "center", gap: 10 },
  centerRow: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 },
  headerRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  headerCenterSlot: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
  },
  headerSpacer: { width: 42, height: 42 },
  headerIconButton: { width: 42, height: 42, alignItems: "center", justifyContent: "center", zIndex: 1 },
  proProgressWrap: {
    alignItems: "center",
    gap: 5,
    minWidth: 72,
  },
  proProgressLabel: {
    color: "#f6e7c1",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  proProgressTrack: {
    width: 72,
    height: 4,
    borderRadius: 999,
    backgroundColor: "rgba(246,231,193,0.22)",
    overflow: "hidden",
    flexDirection: "row",
  },
  proProgressFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: "#d7a435",
  },
  profileMenu: { position: "absolute", right: 0, top: 48, zIndex: 40, minWidth: 170, overflow: "hidden", borderRadius: 16, borderWidth: 1, borderColor: border, backgroundColor: "rgba(9,9,11,0.98)" },
  profileMenuAnchor: { zIndex: 40 },
  profileMenuDismiss: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 30,
  },
  profileMenuItem: { paddingHorizontal: 16, paddingVertical: 13 },
  profileMenuDangerText: { color: "#fca5a5", fontSize: 15, fontWeight: "800", textTransform: "lowercase" },
  unjamPopover: { position: "absolute", width: 200, gap: 4, padding: 12, paddingBottom: 4, borderRadius: 18, borderWidth: 1, borderColor: border, backgroundColor: "#09090b" },
  notifyPopover: { position: "absolute", width: 240, gap: 4, padding: 12, paddingBottom: 4, borderRadius: 18, borderWidth: 1, borderColor: border, backgroundColor: "#09090b" },
  unjamPopoverTitle: { color: "#fff", fontSize: 15, fontWeight: "800", textAlign: "center" },
  confirmOptionYesText: { color: "#fff", fontSize: 16, fontWeight: "800", textTransform: "lowercase" },
  profileMenuMutedText: { color: "#71717a", fontSize: 14, fontWeight: "700", textTransform: "lowercase" },
  blockedUsersList: { gap: 10 },
  blockedUserRow: { flexDirection: "row", alignItems: "center", gap: 12, padding: 12, borderRadius: 18, borderWidth: 1, borderColor: border, backgroundColor: panelSoft },
  blockedUserInfo: { flex: 1, gap: 2 },
  unblockButton: { minHeight: 38, alignItems: "center", justifyContent: "center", borderRadius: 13, borderWidth: 1, borderColor: border, backgroundColor: panel, paddingHorizontal: 13 },
  unblockButtonText: { color: "#fff", fontSize: 13, fontWeight: "800", textTransform: "lowercase" },
  editAvatarButton: { alignSelf: "center", alignItems: "center", gap: 8, paddingVertical: 4 },
  twoCol: { flexDirection: "row", gap: 10 },
  flex1: { flex: 1 },
  profileCentered: { alignItems: "center", gap: 7, paddingVertical: 8 },
  profileVideoDivider: { height: StyleSheet.hairlineWidth, backgroundColor: "rgba(255,255,255,0.28)", marginTop: 4 },
  avatarImage: { backgroundColor: panel },
  avatarFallback: { alignItems: "center", justifyContent: "center", backgroundColor: "#27272a" },
  avatarText: { color: "#fff", fontWeight: "800" },
  goldBadge: { width: 15, height: 15, alignItems: "center", justifyContent: "center" },
  goldBadgeBase: { width: 15, height: 15, borderRadius: 7.5, alignItems: "center", justifyContent: "center", overflow: "hidden", shadowColor: "#f8d363", shadowOpacity: 0.32, shadowRadius: 3, shadowOffset: { width: 0, height: 1 }, elevation: 3 },
  goldBadgeInnerRing: { position: "absolute", width: 13.2, height: 13.2, borderRadius: 6.6, borderWidth: 1, borderColor: "#050505" },
  checkMark: { width: 9, height: 7.2, marginLeft: 0.6, marginTop: -0.6, alignItems: "center", justifyContent: "center" },
  checkStroke: { width: 7.5, height: 4.2, borderLeftWidth: 2.4, borderBottomWidth: 2.4, borderColor: "#020202", transform: [{ rotate: "-45deg" }] },
  feedRoot: { flex: 1, backgroundColor: "#000" },
  feedBootOverlay: { ...StyleSheet.absoluteFillObject, zIndex: 100, backgroundColor: "#000" },
  uploadProgressNavWrap: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 0,
    overflow: "visible",
    zIndex: 50,
  },
  uploadProgressLine: {
    position: "absolute",
    left: 0,
    right: 0,
    height: 2,
    zIndex: 51,
    backgroundColor: "rgba(255,255,255,0.18)",
    overflow: "hidden",
  },
  uploadProgressLineFill: {
    height: "100%",
    backgroundColor: "#fff",
  },
  feedTopBar: {
    position: "absolute",
    left: 0,
    right: 0,
    zIndex: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 18,
  },
  // Same horizontal spacing as feedTopBar, but in-flow for the inbox ScrollView.
  inboxTopBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginHorizontal: -SCREEN_CONTENT_PADDING,
    paddingHorizontal: 18,
  },
  feedRecentFiltersArea: { flex: 1, justifyContent: "center", overflow: "visible" },
  feedRecentFiltersMask: { flex: 1, height: 44 },
  feedRecentFiltersMaskElement: { flex: 1, backgroundColor: "transparent" },
  feedRecentFiltersRow: { flexDirection: "row", alignItems: "center", paddingVertical: 8 },
  feedRecentFilterItem: { alignItems: "center", justifyContent: "center" },
  feedRecentFilterText: {
    color: "#d4d4d8",
    fontSize: 13,
    fontWeight: "600",
    textTransform: "lowercase",
  },
  feedRecentFilterTextActive: { color: "#fff", fontWeight: "700" },
  fullscreenMessageRoot: { flex: 1, backgroundColor: "transparent" },
  fullscreenVideoRoot: { flex: 1, backgroundColor: "transparent", justifyContent: "flex-end" },
  fullscreenAdjacentVideo: { position: "absolute", left: 0, right: 0, height: viewportHeight, backgroundColor: "#000" },
  fullscreenCurrentVideo: { zIndex: 2, elevation: 2 },
  filterButton: { width: 44, height: 44, alignItems: "center", justifyContent: "center" },
  inboxFilterButtonActive: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.28)",
    backgroundColor: "rgba(63,63,70,0.92)",
  },
  feedFilterButton: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    transform: [{ translateY: -2 }],
  },
  feedNearMeButton: { width: 44, height: 44, alignItems: "center", justifyContent: "center" },
  feedNearMeButtonActive: { opacity: 1 },
  feedCaptionRow: { flexDirection: "row", alignItems: "flex-start", gap: 8 },
  filterLookingForRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    marginBottom: -6,
  },
  filterLookingForControl: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  filterLookingForLabel: {
    color: muted,
    fontSize: 15,
    fontWeight: "600",
    textTransform: "lowercase",
  },
  filterLookingForIconSlot: {
    minHeight: 40,
    minWidth: 52,
    alignItems: "center",
    justifyContent: "center",
  },
  feedLookingForIcon: {
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
  },
  feedCaptionText: { flex: 1 },
  nearMeRadiusRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  nearMeRadiusOption: {
    minWidth: 58,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    backgroundColor: "rgba(39,39,42,0.72)",
    alignItems: "center",
  },
  nearMeRadiusOptionActive: {
    borderColor: "rgba(255,255,255,0.28)",
    backgroundColor: "rgba(63,63,70,0.92)",
  },
  nearMeRadiusOptionText: { color: "#a1a1aa", fontSize: 13, fontWeight: "600", textTransform: "lowercase" },
  nearMeRadiusOptionTextActive: { color: "#fff" },
  iconText: { color: "#fff", fontSize: 22, fontWeight: "700" },
  closeIconText: { color: "#fff", fontSize: 28, fontWeight: "500", lineHeight: 30 },
  feedItem: { width: "100%", backgroundColor: "#000", justifyContent: "flex-end", overflow: "visible" },
  feedVideoLayer: { position: "absolute", left: 0, right: 0, top: 0, bottom: 0 },
  feedVideoViewportClip: {
    overflow: "hidden",
  },
  feedPreviewVideoClip: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    overflow: "hidden",
    borderBottomLeftRadius: FEED_PREVIEW_VIDEO_BOTTOM_CORNER_RADIUS,
    borderBottomRightRadius: FEED_PREVIEW_VIDEO_BOTTOM_CORNER_RADIUS,
  },
  feedBufferingIndicator: { ...StyleSheet.absoluteFillObject, alignItems: "center", justifyContent: "center" },
  videoBufferingIndicator: { ...StyleSheet.absoluteFillObject, alignItems: "center", justifyContent: "center" },
  // TikTok-style: no full-frame dim — soft edge fades behind chrome.
  feedTopShade: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    height: Math.round(viewportHeight * 0.22),
  },
  feedBottomShade: {
    position: "absolute",
    left: 0,
    right: 0,
    height: Math.round(viewportHeight * 0.34),
  },
  feedOverlayLayer: { position: "absolute", left: 0, right: 0, top: 0, bottom: 0 },
  feedChromeLockHud: {
    position: "absolute",
    left: 0,
    right: 0,
    zIndex: 8,
    alignItems: "center",
  },
  feedSpeedHud: {
    position: "absolute",
    zIndex: 9,
    alignItems: "center",
  },
  feedSpeedPill: {
    width: FEED_SPEED_PILL_WIDTH,
    height: FEED_SPEED_PILL_HEIGHT,
    paddingVertical: FEED_SPEED_PILL_PADDING_V,
    borderRadius: FEED_SPEED_PILL_WIDTH / 2,
    backgroundColor: "rgba(0,0,0,0.42)",
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.55)",
    alignItems: "center",
    justifyContent: "space-between",
  },
  feedSpeedRow: {
    height: FEED_SPEED_ROW_HEIGHT,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  feedSpeedText: {
    color: "rgba(255,255,255,0.45)",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: -0.3,
  },
  feedSpeedTextSelected: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "800",
  },
  feedChromeLockTrack: {
    width: FEED_CHROME_LOCK_CIRCLE_SIZE,
    alignItems: "center",
  },
  feedChromeLockPath: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    width: FEED_CHROME_LOCK_CIRCLE_SIZE,
    borderRadius: FEED_CHROME_LOCK_CIRCLE_SIZE / 2,
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.55)",
    backgroundColor: "rgba(255,255,255,0.10)",
  },
  feedChromeLockKnob: {
    position: "absolute",
    top: 0,
    width: FEED_CHROME_LOCK_CIRCLE_SIZE,
    height: FEED_CHROME_LOCK_CIRCLE_SIZE,
    borderRadius: FEED_CHROME_LOCK_CIRCLE_SIZE / 2,
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.92)",
    backgroundColor: "rgba(0,0,0,0.28)",
    alignItems: "center",
    justifyContent: "center",
  },
  feedChromeLockTarget: {
    position: "absolute",
    bottom: 0,
    width: FEED_CHROME_LOCK_CIRCLE_SIZE,
    height: FEED_CHROME_LOCK_CIRCLE_SIZE,
    borderRadius: FEED_CHROME_LOCK_CIRCLE_SIZE / 2,
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.35)",
    backgroundColor: "rgba(0,0,0,0.16)",
    alignItems: "center",
    justifyContent: "center",
  },
  feedMeta: { position: "absolute", left: 18, right: 76, gap: 11 },
  feedName: { color: "#fff", fontSize: 20, fontWeight: "800", letterSpacing: -0.3, ...overlayTextShadow },
  feedRole: { color: "#f4f4f5", fontSize: 12, fontWeight: "600", ...overlayTextShadow },
  caption: { color: "#fff", fontSize: 15, lineHeight: 21, ...overlayTextShadow },
  tags: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  tag: { color: "#e4e4e7", fontSize: 14, paddingHorizontal: 12, paddingVertical: 7, borderRadius: 999, backgroundColor: "rgba(255,255,255,0.10)", ...overlayTextShadow },
  tagHighlighted: {
    color: "#fff",
    backgroundColor: "rgba(255,255,255,0.28)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.45)",
  },
  badge: { color: "#fff", fontSize: 11, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 999, backgroundColor: "rgba(255,255,255,0.20)", overflow: "hidden", ...overlayTextShadow },
  actions: { position: "absolute", right: 18, gap: FEED_ACTION_GAP },
  actionButton: { width: 56, height: 56, alignItems: "center", justifyContent: "center" },
  actionText: { color: "#fff", fontSize: 31, lineHeight: 33, textShadowColor: "rgba(0,0,0,0.45)", textShadowRadius: 4, textShadowOffset: { width: 0, height: 1 } },
  actionDotsText: { transform: [{ translateY: -6 }] },
  feedMoreSheetWrap: { flex: 1, justifyContent: "flex-end" },
  feedMoreSheetDismiss: { ...StyleSheet.absoluteFillObject },
  feedMoreSheetCard: { margin: 14, marginBottom: 24, borderRadius: 26, borderWidth: 1, borderColor: "rgba(255,255,255,0.14)", backgroundColor: "rgba(9,9,11,0.98)", paddingVertical: 8, overflow: "hidden" },
  feedMoreMenuItem: { paddingHorizontal: 16, paddingVertical: 13 },
  feedMoreMenuText: { color: "#f4f4f5", fontSize: 15, fontWeight: "700", ...overlayTextShadow },
  feedMoreMenuDangerText: { color: "#fca5a5", fontSize: 15, fontWeight: "800", ...overlayTextShadow },
  fullscreenMessageBar: { position: "absolute", left: 0, right: 0, bottom: 0, minHeight: NAV_BAR_HEIGHT, flexDirection: "row", alignItems: "flex-start", gap: 10, paddingTop: 13, paddingHorizontal: 14, borderTopWidth: 1, borderTopColor: border, backgroundColor: "rgba(10,10,10,0.96)" },
  fullscreenMessageInput: { flex: 1, minHeight: NAV_BAR_ITEM_HEIGHT, borderRadius: 18, borderWidth: 1, borderColor: border, color: "#fff", backgroundColor: panel, paddingHorizontal: 16, fontSize: 16 },
  fullscreenMessageSendFrame: { minHeight: NAV_BAR_ITEM_HEIGHT },
  fullscreenMessageSendButton: { minHeight: NAV_BAR_ITEM_HEIGHT, width: "100%", borderRadius: 18, alignItems: "center", justifyContent: "center", backgroundColor: "#fff" },
  fullscreenMessageSendText: { color: "#000", fontWeight: "800" },
  fullscreenMessageSentTick: { fontSize: 19, lineHeight: 22 },
  videoMenu: { position: "absolute", right: 52, top: 4, minWidth: 132, borderRadius: 16, borderWidth: 1, borderColor: border, backgroundColor: "rgba(9,9,11,0.94)", overflow: "hidden" },
  videoMenuItem: { paddingHorizontal: 16, paddingVertical: 13 },
  videoMenuDangerText: { color: "#fca5a5", fontSize: 15, fontWeight: "800", textTransform: "lowercase", ...overlayTextShadow },
  jamJarIcon: { width: 31, height: 36, alignItems: "center", justifyContent: "flex-end" },
  jamJarLid: { width: 23, height: 7, borderRadius: 3, borderWidth: 2, borderColor: "#fff", marginBottom: -1, overflow: "hidden" },
  jamJarLidSent: { height: 4, borderWidth: 0, backgroundColor: "#fff", borderRadius: 2, marginBottom: 2 },
  jamJarLidSolidFill: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#fff",
    borderRadius: 2,
    margin: -1,
  },
  jamJarBody: { width: 27, height: 27, borderRadius: 9, borderWidth: 2, borderColor: "#fff", overflow: "hidden", justifyContent: "flex-end" },
  jamJarAnimatedFill: {
    width: 23,
    alignSelf: "center",
    backgroundColor: "#fff",
    position: "relative",
  },
  jamJarSmoothWaveSurface: {
    position: "absolute",
    top: -4,
    left: 0,
    width: 23,
    height: 5,
  },
  jamJarBumpWaveWrap: {
    ...StyleSheet.absoluteFillObject,
  },
  jamJarLeak: {
    position: "absolute",
    top: 3,
    alignSelf: "center",
    zIndex: 2,
  },
  jamJarLeakDrop: {
    position: "absolute",
    left: -3,
    top: -6,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#fff",
  },
  jamJarLeakDropSide: {
    left: -2.25,
    top: -4.5,
    width: 4.5,
    height: 4.5,
    borderRadius: 2.25,
  },
  jamJarFill: { height: 7, backgroundColor: "#fff" },
  jamJarFillSent: { height: 21 },
  jamJarEmptyJam: { position: "absolute", left: 0, bottom: 0 },
  jamJarWaveLeft: { position: "absolute", left: -3, top: -4, width: 15, height: 8, borderRadius: 8, backgroundColor: "#fff" },
  jamJarWaveRight: { position: "absolute", right: -4, top: -2, width: 18, height: 7, borderRadius: 9, backgroundColor: "#fff" },
  videoPlaceholder: { flex: 1, alignItems: "center", justifyContent: "center", gap: 18, backgroundColor: "#09090b" },
  emptyFeed: { flex: 1, alignItems: "center", justifyContent: "center", gap: 18, padding: 28 },
  endOfFeed: {
    width: "100%",
    alignSelf: "stretch",
    alignItems: "center",
    justifyContent: "center",
    gap: 18,
    paddingHorizontal: 28,
    backgroundColor: dark,
  },
  endOfFeedFullscreen: {
    flex: 1,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    gap: 18,
    paddingHorizontal: 28,
    paddingBottom: NAV_BAR_HEIGHT,
    backgroundColor: dark,
  },
  emptyText: { color: "#e4e4e7", fontSize: 22, lineHeight: 31, textAlign: "center", fontWeight: "700" },
  modalShade: { position: "absolute", left: 0, right: 0, top: 0, bottom: 0, backgroundColor: "rgba(0,0,0,0.62)" },
  topSheet: { position: "absolute", left: 0, right: 0, top: 0, gap: 10, padding: 22, paddingBottom: 26, borderBottomLeftRadius: 28, borderBottomRightRadius: 28, borderWidth: 1, borderColor: border, backgroundColor: "#09090b" },
  topSheetScroll: { flexShrink: 1 },
  topSheetScrollContent: { gap: 10, paddingBottom: 2 },
  filterSheetSection: { gap: 10 },
  bottomModalWrap: { flex: 1, justifyContent: "flex-end" },
  bottomCard: { gap: 14, padding: 18, paddingBottom: 28, borderTopLeftRadius: 28, borderTopRightRadius: 28, borderWidth: 1, borderColor: border, backgroundColor: "#09090b" },
  jamPromptOverlay: { flex: 1, justifyContent: "center", padding: 22 },
  jamPromptHost: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 60,
  },
  chatOverlayHost: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 70,
  },
  chatOverlaySwipeSurface: {
    flex: 1,
    backgroundColor: "transparent",
  },
  jamPromptShade: { position: "absolute", left: 0, right: 0, top: 0, bottom: 0, backgroundColor: "rgba(0,0,0,0.42)" },
  jamPromptCard: { gap: 14, padding: 18, borderRadius: 28, borderWidth: 1, borderColor: border, backgroundColor: "rgba(9,9,11,0.92)" },
  confirmModalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 48,
  },
  confirmModalCard: {
    width: "100%",
    maxWidth: 260,
    gap: 8,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: border,
    backgroundColor: "#09090b",
  },
  confirmModalTitle: { color: "#fff", fontSize: 16, fontWeight: "800", textAlign: "center" },
  confirmModalMessage: { color: "#a1a1aa", fontSize: 13, lineHeight: 18, textAlign: "center" },
  confirmModalActions: { flexDirection: "row", gap: 6, marginTop: 2 },
  confirmModalOption: { flex: 1, minHeight: 36, alignItems: "center", justifyContent: "center" },
  cardTitle: { color: "#fff", fontSize: 20, fontWeight: "800" },
  reportReasonList: { gap: 8 },
  reportReasonButton: { minHeight: 48, justifyContent: "center", borderRadius: 16, borderWidth: 1, borderColor: border, backgroundColor: panel, paddingHorizontal: 16 },
  reportReasonText: { color: "#fff", fontSize: 15, fontWeight: "800" },
  smallPill: { paddingHorizontal: 14, paddingVertical: 9, borderRadius: 13, borderWidth: 1, borderColor: border, backgroundColor: panel },
  smallPillText: { color: "#e4e4e7", fontWeight: "700" },
  iconCircle: { width: 42, height: 42, borderRadius: 21, borderWidth: 1, borderColor: border, backgroundColor: panelSoft, alignItems: "center", justifyContent: "center" },
  chatBackButton: { width: 36, height: 42, alignItems: "center", justifyContent: "center" },
  previewBox: { overflow: "hidden", borderRadius: 28, borderWidth: 1, borderColor: border, backgroundColor: "#000" },
  previewVideo: { width: "100%", aspectRatio: 9 / 16, backgroundColor: "#000" },
  createThumbnailLoader: { alignSelf: "center", marginVertical: 8, alignItems: "center", gap: 8 },
  createThumbnailFilmstripWrap: {
    height: CREATE_THUMBNAIL_FILMSTRIP_FRAME_HEIGHT + 6,
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor: "#000",
    borderWidth: 1,
    borderColor: border,
    justifyContent: "center",
  },
  createThumbnailFilmstripRow: { flexDirection: "row" },
  createThumbnailFilmstripGestureArea: { flex: 1, justifyContent: "center" },
  createThumbnailFilmstripSelector: {
    position: "absolute",
    top: 0,
    borderWidth: 3,
    borderColor: "#fff",
    borderRadius: 8,
    zIndex: 2,
  },
  createLookingForToggle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 12,
    alignSelf: "stretch",
  },
  createLookingForToggleCopy: {
    flex: 1,
    gap: 2,
    justifyContent: "center",
  },
  createLookingForToggleTitle: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "700",
    textTransform: "lowercase",
  },
  createLookingForToggleHelper: {
    color: "#a1a1aa",
    fontSize: 13,
    lineHeight: 18,
  },
  createDetailsComposerRow: { flexDirection: "row", gap: 12, alignItems: "stretch" },
  createDetailsCaptionInput: {
    flex: 1,
    minHeight: CREATE_DETAILS_PREVIEW_HEIGHT,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: border,
    color: "#fff",
    backgroundColor: panel,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
  },
  createDetailsVideoTap: {
    width: CREATE_DETAILS_PREVIEW_WIDTH,
    height: CREATE_DETAILS_PREVIEW_HEIGHT,
    borderRadius: 16,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: border,
    backgroundColor: "#000",
  },
  createDetailsVideoTapImage: { width: "100%", height: "100%" },
  createDetailsVideoTapFallback: {
    flex: 1,
    backgroundColor: "#18181b",
    alignItems: "center",
    justifyContent: "center",
  },
  createDetailsVideoTapBadge: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingVertical: 6,
    backgroundColor: "rgba(0,0,0,0.55)",
  },
  createDetailsVideoTapBadgeText: {
    color: "#fff",
    fontSize: 11,
    fontWeight: "800",
    textAlign: "center",
    textTransform: "lowercase",
  },
  createPostPreviewBackdrop: { flex: 1, backgroundColor: "#000" },
  createPostPreviewFrame: { flex: 1, backgroundColor: "#000", overflow: "hidden" },
  createPostPreviewVideo: { ...StyleSheet.absoluteFillObject },
  createPostPreviewFilter: { ...StyleSheet.absoluteFillObject },
  createPostPreviewTextOverlay: {
    position: "absolute",
    zIndex: 4,
    maxWidth: "85%",
  },
  createPostPreviewTextOverlayText: {
    color: "rgba(255,255,255,0.88)",
    fontSize: TEXT_OVERLAY_BASE_FONT_SIZE,
    lineHeight: Math.round(TEXT_OVERLAY_BASE_FONT_SIZE * 1.25),
    textAlign: "center",
    textShadowColor: "rgba(0,0,0,0.55)",
    textShadowRadius: 1.5,
    textShadowOffset: { width: 0, height: 1 },
  },
  createPostPreviewShade: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.18)",
  },
  createPostPreviewMeta: { position: "absolute", left: 18, right: 76, bottom: 122, gap: 11 },
  createPostPreviewNavBarPlaceholder: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#000",
    zIndex: 6,
  },
  createPostPreviewClose: {
    position: "absolute",
    right: 16,
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: border,
    backgroundColor: "rgba(9,9,11,0.72)",
    zIndex: 10,
  },
  createEditNextBand: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 5,
    alignItems: "center",
    justifyContent: "center",
  },
  createEditKeyboardDismissBand: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 0,
  },
  createEditKeyboardDismissLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 1,
  },
  createEditNextPill: {
    minHeight: 48,
    minWidth: 120,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 999,
    backgroundColor: "#fff",
    paddingHorizontal: 28,
    zIndex: 1,
  },
  createEditNextText: { color: "#000", fontSize: 16, fontWeight: "900", textTransform: "lowercase" },
  createEditToolPanel: {
    position: "absolute",
    left: 18,
    right: 72,
    zIndex: 6,
    gap: 10,
    paddingHorizontal: 4,
  },
  createTrimToolPanel: {
    position: "absolute",
    left: 0,
    right: 0,
    zIndex: 6,
    alignItems: "center",
    paddingHorizontal: 18,
  },
  createTrimToolPanelContent: {
    width: "100%",
    maxWidth: 360,
    gap: 8,
  },
  createEditUploadProgressWrap: {
    position: "absolute",
    left: 18,
    right: 18,
    zIndex: 6,
  },
  createFilterOverlay: { ...StyleSheet.absoluteFillObject },
  createTextOverlayDraggable: {
    position: "absolute",
    zIndex: 2,
    maxWidth: "85%",
    overflow: "visible",
  },
  createTextOverlayPinchCapture: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 2,
  },
  createTextOverlaySnapGuideVertical: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: "50%",
    width: 1,
    marginLeft: -0.5,
    backgroundColor: "#FFE566",
    zIndex: 1,
  },
  createTextOverlaySnapGuideHorizontal: {
    position: "absolute",
    left: 0,
    right: 0,
    top: "50%",
    height: 1,
    marginTop: -0.5,
    backgroundColor: "#FFE566",
    zIndex: 1,
  },
  createTextOverlayPreviewText: {
    color: "#fff",
    fontSize: TEXT_OVERLAY_BASE_FONT_SIZE,
    lineHeight: Math.round(TEXT_OVERLAY_BASE_FONT_SIZE * 1.25),
    textAlign: "center",
    flexShrink: 1,
    textShadowColor: "rgba(0,0,0,0.55)",
    textShadowRadius: 1.5,
    textShadowOffset: { width: 0, height: 1 },
  },
  createTextOverlayInput: {
    color: "#fff",
    fontSize: TEXT_OVERLAY_BASE_FONT_SIZE,
    lineHeight: Math.round(TEXT_OVERLAY_BASE_FONT_SIZE * 1.25),
    textAlign: "center",
    textShadowColor: "rgba(0,0,0,0.55)",
    textShadowRadius: 1.5,
    textShadowOffset: { width: 0, height: 1 },
    padding: 0,
    margin: 0,
    minWidth: 18,
    backgroundColor: "transparent",
    includeFontPadding: false,
  },
  createTextOverlayActionMenu: {
    position: "absolute",
    zIndex: 8,
    alignItems: "center",
  },
  createTextOverlayActionCaret: {
    position: "absolute",
    top: 0,
    width: 0,
    height: 0,
    borderLeftWidth: 8,
    borderRightWidth: 8,
    borderBottomWidth: 9,
    borderLeftColor: "transparent",
    borderRightColor: "transparent",
    borderBottomColor: "rgba(20,20,22,0.96)",
    zIndex: 2,
  },
  createTextOverlayActionBubble: {
    marginTop: 8,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(20,20,22,0.96)",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    overflow: "hidden",
  },
  createTextOverlayActionButton: {
    paddingHorizontal: 18,
    paddingVertical: 11,
  },
  createTextOverlayActionButtonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "800",
    textTransform: "lowercase",
  },
  createTextOverlayActionEffectButton: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    minWidth: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  createTextOverlayActionEffectGlyph: {
    color: "#fff",
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "900",
    textAlign: "center",
    includeFontPadding: false,
  },
  createTextOverlayActionDeleteText: {
    color: "#f87171",
    fontSize: 14,
    fontWeight: "800",
    textTransform: "lowercase",
  },
  createTextOverlayActionDivider: {
    width: 1,
    alignSelf: "stretch",
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  createTrimHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 10 },
  createTrimDuration: { color: "#fff", fontSize: 14, fontWeight: "900" },
  createTrimFilmstripOuter: {
    position: "relative",
    height: CREATE_TRIM_FILMSTRIP_HEIGHT,
    justifyContent: "center",
  },
  createTrimFilmstrip: {
    height: CREATE_TRIM_FILMSTRIP_HEIGHT,
    borderRadius: CREATE_TRIM_FILMSTRIP_RADIUS,
    overflow: "hidden",
    backgroundColor: "#18181b",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    position: "relative",
  },
  createTrimFilmstripLoading: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  createTrimFilmstripFrames: {
    flex: 1,
    flexDirection: "row",
  },
  createTrimFilmstripFrame: {
    flex: 1,
    height: "100%",
  },
  createTrimFilmstripFramePlaceholder: {
    flex: 1,
    height: "100%",
    backgroundColor: "#27272a",
  },
  createTrimFilmstripDim: {
    position: "absolute",
    top: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.55)",
  },
  createTrimFilmstripSelection: {
    position: "absolute",
    top: 0,
    bottom: 0,
    borderWidth: 2,
    borderColor: "#fff",
  },
  createTrimProgressTrack: {
    position: "absolute",
    top: 0,
    bottom: 0,
    zIndex: 3,
    overflow: "hidden",
  },
  createTrimProgressFill: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    backgroundColor: "rgba(255,255,255,0.18)",
  },
  createTrimPlayhead: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    width: 2,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOpacity: 0.45,
    shadowRadius: 2,
    shadowOffset: { width: 0, height: 0 },
  },
  createTrimHandleTab: {
    position: "absolute",
    top: 0,
    width: CREATE_TRIM_HANDLE_WIDTH,
    height: CREATE_TRIM_FILMSTRIP_HEIGHT,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fafafa",
    borderColor: "#fff",
    borderTopWidth: 2,
    borderBottomWidth: 2,
    zIndex: 4,
  },
  createTrimHandleTabStart: {
    borderRightWidth: 2,
  },
  createTrimHandleTabStartFlush: {
    borderLeftWidth: 2,
    borderTopLeftRadius: CREATE_TRIM_FILMSTRIP_RADIUS - 1,
    borderBottomLeftRadius: CREATE_TRIM_FILMSTRIP_RADIUS - 1,
  },
  createTrimHandleTabEnd: {
    borderLeftWidth: 2,
  },
  createTrimHandleTabEndFlush: {
    borderRightWidth: 2,
    borderTopRightRadius: CREATE_TRIM_FILMSTRIP_RADIUS - 1,
    borderBottomRightRadius: CREATE_TRIM_FILMSTRIP_RADIUS - 1,
  },
  createFilterList: { gap: 10, paddingVertical: 2 },
  createFilterListCompact: { gap: 10, paddingVertical: 0, paddingHorizontal: 16 },
  createFilterOption: { width: 70, gap: 6, alignItems: "center" },
  createFilterOptionCompact: { width: 44 },
  createFilterThumbRing: {
    width: 64,
    height: 78,
    borderRadius: 16,
    borderWidth: CREATE_FILTER_THUMB_BORDER_WIDTH,
    borderColor: "transparent",
  },
  createFilterThumbRingCompact: { width: 44, height: 44, borderRadius: 22 },
  createFilterThumbRingActive: { borderColor: "#fff" },
  createFilterThumbInner: {
    flex: 1,
    borderRadius: 16 - CREATE_FILTER_THUMB_BORDER_WIDTH,
    overflow: "hidden",
    backgroundColor: "#18181b",
  },
  createFilterThumbInnerCompact: { borderRadius: 22 - CREATE_FILTER_THUMB_BORDER_WIDTH },
  createTextFontThumbInner: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(24,24,27,0.92)",
    borderRadius: 22 - CREATE_FILTER_THUMB_BORDER_WIDTH,
    overflow: "hidden",
  },
  createTextFontThumbSample: {
    color: "#fff",
    fontSize: 20,
    fontWeight: "800",
  },
  createFilterThumbImage: { width: "100%", height: "100%" },
  createFilterThumbFallback: { flex: 1, backgroundColor: "#27272a" },
  createFilterLabel: { color: "#d4d4d8", fontSize: 12, fontWeight: "800" },
  createFilterNameFlashRoot: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  createFilterNameFlashText: {
    color: "#fff",
    fontSize: 34,
    fontWeight: "700",
    fontFamily: Platform.select({
      ios: "Book Antiqua",
      android: "serif",
      default: "Book Antiqua",
    }),
    letterSpacing: 0.2,
    textAlign: "center",
    textShadowColor: "rgba(0,0,0,0.55)",
    textShadowRadius: 10,
    textShadowOffset: { width: 0, height: 2 },
  },
  createFilterLabelCompact: { fontSize: 10 },
  createEditUploadProgress: { height: 5, borderRadius: 999, backgroundColor: "rgba(255,255,255,0.12)", overflow: "hidden" },
  createCameraRoot: { flex: 1, backgroundColor: "#000" },
  createCameraViewport: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    overflow: "hidden",
    backgroundColor: "#000",
    borderBottomLeftRadius: FEED_VIDEO_BOTTOM_CORNER_RADIUS,
    borderBottomRightRadius: FEED_VIDEO_BOTTOM_CORNER_RADIUS,
  },
  createCameraPermission: { ...StyleSheet.absoluteFillObject, alignItems: "center", justifyContent: "center", gap: 16, padding: 28, backgroundColor: "#000" },
  createCameraTapLayer: { ...StyleSheet.absoluteFillObject, zIndex: 1 },
  createCameraFocusReticle: {
    position: "absolute",
    width: CREATE_CAMERA_FOCUS_RETICLE_SIZE,
    height: CREATE_CAMERA_FOCUS_RETICLE_SIZE,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 4,
  },
  createCameraFocusReticleCircle: {
    width: CREATE_CAMERA_FOCUS_RETICLE_SIZE * 0.78,
    height: CREATE_CAMERA_FOCUS_RETICLE_SIZE * 0.78,
    borderRadius: (CREATE_CAMERA_FOCUS_RETICLE_SIZE * 0.78) / 2,
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.95)",
    backgroundColor: "transparent",
  },
  createCameraExposureRail: {
    position: "absolute",
    right: -14,
    top: CREATE_CAMERA_FOCUS_RETICLE_SIZE * 0.06,
    bottom: CREATE_CAMERA_FOCUS_RETICLE_SIZE * 0.06,
    width: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  createCameraExposureLine: {
    position: "absolute",
    top: 0,
    bottom: 0,
    width: StyleSheet.hairlineWidth * 2,
    backgroundColor: "rgba(255,255,255,0.95)",
  },
  createCameraExposureDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#fff",
  },
  createCameraFilterPreview: { zIndex: 2 },
  createCameraScreenFlash: { zIndex: 3 },
  createCameraCountdownOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 6,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.28)",
  },
  createCameraCountdownText: { color: "#fff", fontSize: 88, fontWeight: "900", letterSpacing: -2 },
  createCameraTopBar: { position: "absolute", left: 18, right: 18, zIndex: 5, flexDirection: "row", alignItems: "center", justifyContent: "flex-start" },
  createCameraSideRail: { position: "absolute", right: 18, zIndex: 5, gap: 16, alignItems: "center" },
  createCameraControlButton: {
    width: CREATE_CAMERA_CONTROL_BUTTON_SIZE,
    height: CREATE_CAMERA_CONTROL_BUTTON_SIZE,
    alignItems: "center",
    justifyContent: "center",
  },
  createCameraSideRailText: { color: "#fff", fontSize: 16, fontWeight: "900" },
  createCameraCloseIconText: { color: "#fff", fontSize: 32, fontWeight: "500", lineHeight: 34 },
  createCameraFilterSheetWrap: { ...StyleSheet.absoluteFillObject, zIndex: 8 },
  createCameraFilterDismiss: { ...StyleSheet.absoluteFillObject },
  createCameraFilterBand: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    overflow: "hidden",
  },
  createTextFontPickerBand: {
    justifyContent: "center",
  },
  createTextFontPickerScroll: {
    flexGrow: 0,
  },
  createTextFontPickerList: {
    gap: 10,
    paddingHorizontal: 16,
    alignItems: "center",
  },
  createCameraFilterFloat: { position: "absolute", left: 0, right: 0, alignItems: "center" },
  createCameraBottomBar: {
    position: "absolute",
    left: 28,
    right: 28,
    zIndex: 5,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  createLibraryButton: {
    position: "absolute",
    left: 18,
    zIndex: 5,
    width: 58,
    height: 58,
    borderRadius: 16,
    overflow: "hidden",
    borderWidth: 2,
    borderColor: "#fff",
    backgroundColor: "rgba(24,24,27,0.72)",
  },
  createLibraryThumbnail: { width: "100%", height: "100%" },
  createRecordButton: {
    width: CREATE_CAMERA_RECORD_BUTTON_SIZE,
    height: CREATE_CAMERA_RECORD_BUTTON_SIZE,
    borderRadius: CREATE_CAMERA_RECORD_BUTTON_SIZE / 2,
    borderWidth: CREATE_CAMERA_RECORD_BUTTON_BORDER_WIDTH,
    borderColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  createCameraHint: { position: "absolute", left: 0, right: 0, zIndex: 5, textAlign: "center", color: "#fff", fontSize: 13, fontWeight: "800", textTransform: "lowercase" },
  progressTrack: { height: 8, borderRadius: 999, backgroundColor: "rgba(255,255,255,0.12)", overflow: "hidden" },
  progressFill: { height: "100%", backgroundColor: "#fff" },
  segmented: { alignSelf: "flex-start", flexDirection: "row", borderRadius: 14, padding: 4, borderWidth: 1, borderColor: border, backgroundColor: panel },
  segment: { paddingHorizontal: 18, paddingVertical: 9, borderRadius: 10 },
  segmentActive: { backgroundColor: "#fff" },
  segmentText: { color: "#d4d4d8", fontSize: 15, textTransform: "lowercase" },
  segmentTextActive: { color: "#000", fontWeight: "800" },
  list: { gap: 10 },
  listCard: { flexDirection: "row", alignItems: "center", gap: 12, padding: 13, borderRadius: 22, borderWidth: 1, borderColor: border, backgroundColor: panelSoft },
  listTitle: { color: "#fff", fontSize: 20, fontWeight: "800" },
  conversationRow: { flexDirection: "row", alignItems: "center", gap: 12, paddingVertical: 15, borderBottomWidth: 1, borderBottomColor: border },
  subdued: { opacity: 0.7 },
  alignEnd: { alignItems: "flex-end", gap: 5 },
  unreadDot: { width: 9, height: 9, borderRadius: 4.5, backgroundColor: "#ec4899" },
  emptyCard: { padding: 18, borderRadius: 22, borderWidth: 1, borderColor: border, backgroundColor: panelSoft },
  profileSavedEmptyText: {
    color: muted,
    fontSize: 15,
    lineHeight: 22,
    textAlign: "center",
    paddingVertical: 36,
    paddingHorizontal: 16,
  },
  inboxEmptyText: {
    color: muted,
    fontSize: 15,
    lineHeight: 22,
    textAlign: "center",
    paddingVertical: 28,
    paddingHorizontal: 12,
  },
  chatHeader: { flexDirection: "row", alignItems: "center", gap: 12, padding: 16, borderBottomWidth: 1, borderBottomColor: border },
  chatProfileTarget: { flexDirection: "row", alignItems: "center", gap: 12, flex: 1 },
  chatContent: { flexGrow: 1, gap: 10, padding: 16 },
  chatLoadOlderButton: {
    alignSelf: "center",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.08)",
    marginBottom: 6,
  },
  chatLoadOlderText: { color: "#d4d4d8", fontSize: 13, fontWeight: "600" },
  messageWrap: { maxWidth: "82%", gap: 6 },
  messageWrapIn: { alignSelf: "flex-start" },
  messageWrapOut: { alignSelf: "flex-end" },
  bubble: { maxWidth: "100%", paddingHorizontal: 16, paddingVertical: 12, borderRadius: 22 },
  bubbleIn: { alignSelf: "flex-start", backgroundColor: panel },
  bubbleOut: { alignSelf: "flex-end", backgroundColor: "#fff" },
  bubbleWithVideo: { marginTop: -22, zIndex: 1 },
  messageVideoThumbnailWrap: { width: 190, height: 260, borderRadius: 20, overflow: "hidden", backgroundColor: "#000" },
  messageVideoThumbnailIn: { alignSelf: "flex-start" },
  messageVideoThumbnailOut: { alignSelf: "flex-end" },
  messageVideoThumbnail: { width: "100%", height: "100%" },
  bubbleText: { color: "#fff", fontSize: 15, lineHeight: 22 },
  bubbleTextOut: { color: "#000" },
  messageContextMenu: { alignSelf: "flex-end", minWidth: 128, borderRadius: 16, borderWidth: 1, borderColor: border, backgroundColor: "rgba(9,9,11,0.96)", overflow: "hidden" },
  messageContextItem: { paddingHorizontal: 16, paddingVertical: 12 },
  messageContextText: { color: "#fff", fontSize: 15, fontWeight: "700", textTransform: "lowercase" },
  messageContextDangerText: { color: "#fca5a5", fontSize: 15, fontWeight: "800", textTransform: "lowercase" },
  editMessageBox: { gap: 8, minWidth: 180 },
  editMessageInput: { color: "#000", fontSize: 15, lineHeight: 22, padding: 0, minHeight: 28 },
  editMessageActions: { flexDirection: "row", justifyContent: "flex-end", gap: 14 },
  editMessageCancel: { color: "#52525b", fontSize: 13, fontWeight: "700", textTransform: "lowercase" },
  editMessageSave: { color: "#000", fontSize: 13, fontWeight: "900", textTransform: "lowercase" },
  composer: { flexDirection: "row", gap: 10, paddingHorizontal: 12, paddingTop: 12, paddingBottom: 0, borderTopWidth: 1, borderTopColor: border },
  chatComposerDock: {
    backgroundColor: dark,
  },
  sendButton: { paddingHorizontal: 16, borderRadius: 18, alignItems: "center", justifyContent: "center", backgroundColor: "#fff" },
  sendButtonText: { color: "#000", fontWeight: "800" },
  profileTabSliderViewport: {
    overflow: "hidden",
    marginHorizontal: -SCREEN_CONTENT_PADDING,
  },
  profileTabSliderTrack: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  profileTabPane: {
    width: viewportWidth,
    paddingHorizontal: SCREEN_CONTENT_PADDING,
  },
  profileLibraryTabs: {
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    marginTop: 2,
    marginBottom: 4,
  },
  profileLibraryTabText: {
    color: "#71717a",
    fontSize: 16,
    fontWeight: "500",
    textTransform: "lowercase",
  },
  profileLibraryTabTextActive: {
    color: "#fff",
    fontWeight: "800",
  },
  profileLibraryTabDivider: {
    width: StyleSheet.hairlineWidth,
    height: 14,
    backgroundColor: "#52525b",
  },
  grid: { width: viewportWidth, flexDirection: "row", flexWrap: "wrap", gap: PROFILE_GRID_GAP, marginTop: 8, marginHorizontal: -SCREEN_CONTENT_PADDING },
  gridItem: {
    width: PROFILE_GRID_ITEM_WIDTH,
    aspectRatio: 9 / 16,
    overflow: "hidden",
    alignItems: "flex-end",
    justifyContent: "flex-end",
    padding: 8,
    backgroundColor: "#000",
  },
  gridPinPreview: {
    position: "absolute",
    overflow: "hidden",
    borderRadius: 16,
    backgroundColor: "#000",
    shadowColor: "#000",
    shadowOpacity: 0.45,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 12,
  },
  gridPinPreviewDim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#000",
    borderRadius: 16,
  },
  profileGridLoadingBlur: {
    width: viewportWidth,
    marginTop: 8,
    marginHorizontal: -SCREEN_CONTENT_PADDING,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    backgroundColor: "rgba(39,39,42,0.72)",
  },
  gridThumbPlaceholder: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#3f3f46",
  },
  gridPinnedBadge: {
    position: "absolute",
    top: 6,
    left: 6,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  gridPinMenuRoot: {
    flex: 1,
  },
  gridPinMenuCardWrap: {
    position: "absolute",
    width: 148,
    height: 52,
  },
  gridPinMenuCard: {
    width: 148,
    height: 52,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: border,
    backgroundColor: "rgba(9,9,11,0.96)",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.35,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 8,
  },
  gridPendingOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "rgba(0,0,0,0.28)",
  },
  gridPendingStatusText: {
    color: "rgba(255,255,255,0.9)",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  gridPendingErrorOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "rgba(0,0,0,0.55)",
    paddingHorizontal: 10,
  },
  gridPendingErrorText: { color: "rgba(255,255,255,0.82)", fontSize: 11, textAlign: "center" },
  gridPendingRetryButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.35)",
    paddingHorizontal: 12,
    paddingVertical: 5,
  },
  gridPendingRetryText: { color: "#fff", fontSize: 11, fontWeight: "700", textTransform: "lowercase" },
  uploadProgressRingWrap: { alignItems: "center", justifyContent: "center" },
  profilePostedToast: {
    position: "absolute",
    alignSelf: "center",
    left: "28%",
    right: "28%",
    zIndex: 40,
    backgroundColor: "rgba(255,255,255,0.96)",
    borderRadius: 999,
    paddingVertical: 10,
    paddingHorizontal: 18,
    alignItems: "center",
  },
  profilePostedToastText: { color: "#000", fontWeight: "700", fontSize: 14 },
  feedReplayToast: {
    position: "absolute",
    alignSelf: "center",
    left: 28,
    right: 28,
    zIndex: 40,
    backgroundColor: "rgba(255,255,255,0.72)",
    borderRadius: 999,
    paddingVertical: 10,
    paddingHorizontal: 18,
    alignItems: "center",
  },
  feedReplayToastText: {
    color: "rgba(0,0,0,0.88)",
    fontWeight: "700",
    fontSize: 13,
    textAlign: "center",
    textTransform: "lowercase",
  },
  gridCaption: { color: "#fff", fontSize: 11, lineHeight: 15, fontWeight: "600", ...overlayTextShadow },
  lockedOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(10,10,10,0.28)",
  },
  lockedText: { color: "#fff", textAlign: "center", fontSize: 11, fontWeight: "800", ...overlayTextShadow },
  profileLockGate: {
    position: "absolute",
    left: -SCREEN_CONTENT_PADDING,
    right: -SCREEN_CONTENT_PADDING,
    bottom: 0,
    zIndex: 4,
  },
  profileLockGateMessage: {
    position: "absolute",
    left: 0,
    right: 0,
    alignItems: "center",
    paddingHorizontal: 28,
  },
  profileLockGateText: {
    color: "#fff",
    textAlign: "center",
    fontSize: 15,
    lineHeight: 21,
    fontWeight: "800",
    ...overlayTextShadow,
  },
  settingsOverlay: { flex: 1, alignItems: "flex-end" },
  settingsBackdrop: { position: "absolute", left: 0, right: 0, top: 0, bottom: 0, backgroundColor: "rgba(0,0,0,0.42)" },
  settingsDrawer: { position: "absolute", right: 0, top: 0, bottom: 0, borderLeftWidth: 1, borderLeftColor: border, backgroundColor: "#09090b", shadowColor: "#000", shadowOpacity: 0.35, shadowRadius: 22, shadowOffset: { width: -8, height: 0 }, elevation: 16 },
  settingsPanel: { flex: 1, backgroundColor: "#09090b", paddingHorizontal: 20 },
  settingsPanelScroll: { flex: 1 },
  settingsPanelScrollContent: { gap: 8, paddingBottom: 12 },
  settingsButton: { paddingVertical: 14, paddingHorizontal: 10, borderRadius: 16 },
  settingsToggleGroup: { marginTop: 10, gap: 0 },
  settingsLocationGroup: { gap: 0 },
  // Match settingsRow vertical rhythm (14) so "near me radius" sits evenly
  // under "share live location" like light mode ↔ share live location.
  settingsNearMeSection: { gap: 8, paddingTop: 14, paddingBottom: 14, paddingHorizontal: 10 },
  settingsLiveLocationCopy: {
    color: muted,
    fontSize: 13,
    lineHeight: 18,
    paddingHorizontal: 10,
    paddingBottom: 8,
  },
  settingsRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingVertical: 14, paddingHorizontal: 10 },
  settingsRowLabel: { flex: 1, paddingRight: 12 },
  settingsText: { color: "#e4e4e7", fontSize: 15, textTransform: "lowercase" },
  settingsSwitch: { alignSelf: "center" },
  notificationSettingsSection: { gap: 4, paddingTop: 8 },
  notificationSettingsCopy: { color: muted, fontSize: 14, lineHeight: 22, paddingHorizontal: 10, paddingBottom: 4 },
  notificationCategoryPicker: { gap: 10, paddingTop: 4 },
  notificationCategoryPickerHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 2,
  },
  notificationConfirmButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
  },
  notificationConfirmText: { color: "#000", fontSize: 18, lineHeight: 20, fontWeight: "800" },
  legalTabRow: { flexDirection: "row", marginTop: 8, borderBottomWidth: 1, borderBottomColor: border },
  legalTab: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    borderBottomWidth: 2,
    borderBottomColor: "transparent",
    marginBottom: -1,
  },
  legalTabActive: { borderBottomColor: "#fff" },
  legalTabText: { color: "#71717a", fontSize: 14, fontWeight: "600", textAlign: "center", textTransform: "lowercase" },
  legalTabTextActive: { color: "#fff", fontWeight: "800" },
  legalCopy: { color: "#a1a1aa", fontSize: 15, lineHeight: 24, paddingTop: 18 },
  logoutButton: {
    marginTop: 8,
    paddingVertical: 15,
    paddingHorizontal: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: border,
  },
  logoutText: { color: "#fca5a5", fontSize: 15, textTransform: "lowercase" },
  nav: { position: "absolute", left: 0, right: 0, bottom: 0, minHeight: NAV_BAR_HEIGHT, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 10, paddingTop: 12, paddingHorizontal: 14, borderTopWidth: 1, borderTopColor: border, backgroundColor: "rgba(10,10,10,0.96)" },
  navItem: { height: 58, minWidth: 58, borderRadius: 18, borderWidth: 1, borderColor: border, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 8, paddingHorizontal: 14 },
  navItemActive: { minWidth: 132, borderColor: "#93c5fd", backgroundColor: panel },
  navIcon: { color: "#fff", fontSize: 23 },
  navLabel: { color: "#fff", fontSize: 16, textTransform: "lowercase" },
  gridNavIcon: { width: 23, height: 23, flexDirection: "row", flexWrap: "wrap", gap: 4 },
  gridNavCell: { width: 9, height: 9, borderWidth: 1.8, borderColor: "#fff", borderRadius: 3 },
  mailIconWrap: { width: 33, height: 30, alignItems: "center", justifyContent: "center" },
  mailIcon: { width: 26, height: 19, borderColor: "#fff" },
  // Outer = black ring; inner = red fill — avoids red bleeding past the outline.
  mailBadge: {
    position: "absolute",
    right: -3,
    top: -4,
    minWidth: 17,
    height: 17,
    padding: 1.5,
    borderRadius: 999,
    backgroundColor: "rgba(10,10,10,0.96)",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  mailBadgeInner: {
    minWidth: 14,
    minHeight: 14,
    paddingHorizontal: 3,
    borderRadius: 999,
    backgroundColor: "#ef4444",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  mailBadgeText: { color: "#fff", fontSize: 10, lineHeight: 12, fontWeight: "900" },
  createNav: { width: 66, height: 66, borderRadius: 18, alignItems: "center", justifyContent: "center", backgroundColor: "#fff" },
  createNavText: { color: "#000", fontSize: 38, lineHeight: 41, fontWeight: "600" },
  toast: { position: "absolute", top: 76, left: 18, right: 18, zIndex: 30, alignItems: "center" },
  toastText: { color: "#fecaca", paddingHorizontal: 14, paddingVertical: 9, borderRadius: 999, overflow: "hidden", backgroundColor: "rgba(127,29,29,0.82)" },
  inboxNotificationWrap: {
    position: "absolute",
    left: 18,
    right: 18,
    zIndex: 80,
    alignItems: "center",
  },
  inboxNotificationCard: {
    maxWidth: "100%",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
    backgroundColor: "rgba(9,9,11,0.94)",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  inboxNotificationText: {
    color: "#fff",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "600",
    textAlign: "center",
  },
};


type AppStyle = ViewStyle | TextStyle | ImageStyle;
type AppNamedStyles = Record<string, AppStyle>;
export type AppStyleSet = Record<keyof typeof baseStyles, StyleProp<AppStyle>>;

export const darkStyles = StyleSheet.create(baseStyles as unknown as AppNamedStyles) as AppStyleSet;
export const lightStyles = StyleSheet.create(createLightStyles(baseStyles) as unknown as AppNamedStyles) as AppStyleSet;
export const styles = new Proxy(darkStyles, {
  get(target, property: keyof typeof darkStyles) {
    return activeThemeMode === "light" ? lightStyles[property] : target[property];
  },
}) as AppStyleSet;
